export const references = [
    {   
        name: 'The Avengers',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Symbol_from_Marvel%27s_The_Avengers_logo.svg/1754px-Symbol_from_Marvel%27s_The_Avengers_logo.svg.png',
        startdate: '10/Jan/1996',
        enddate: '02/Feb/2000',
        role: 'Calculations specialist',
        description: 'Calulate the trajectory of the Moon each day to ensure it is not moving.',
        url: 'https://marvelcinematicuniverse.fandom.com/es/wiki/The_Avengers',
    },
    {
        name: 'Nasa',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/2449px-NASA_logo.svg.png',
        startdate: '3/Feb/2000',
        enddate: '01/12/2003',
        role: 'Cofee maker',
        description: 'As head of the division of coffee makers in NASA the main goal was to serve hot cofee to all the employees.',
        url: 'https://www.nasa.gov/', 
    },
    {   
        name: 'FBI',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/FBI_Badge.png',
        startdate: '10/Jan/2004',
        enddate: '02/Feb/1812',
        role: 'Inteligence meter',
        description: 'Calculate de intelligence of the agents in the field of being humans.',
        url: 'https://www.fbi.gov/',
    },
    {   
        name: 'The Avengers',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Symbol_from_Marvel%27s_The_Avengers_logo.svg/1754px-Symbol_from_Marvel%27s_The_Avengers_logo.svg.png',
        startdate: '10/Jan/1996',
        enddate: '02/Feb/2000',
        role: 'Calculations specialist',
        description: 'Calulate the trajectory of the Moon each day to ensure it is not moving.',
        url: 'https://marvelcinematicuniverse.fandom.com/es/wiki/The_Avengers',
    },
    {
        name: 'Nasa',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/2449px-NASA_logo.svg.png',
        startdate: '3/Feb/2000',
        enddate: '01/12/2003',
        role: 'Cofee maker',
        description: 'As head of the division of coffee makers in NASA the main goal was to serve hot cofee to all the employees.',
        url: 'https://www.nasa.gov/', 
    },
    {   
        name: 'FBI',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/FBI_Badge.png',
        startdate: '10/Jan/2004',
        enddate: '02/Feb/1812',
        role: 'Inteligence meter',
        description: 'Calculate de intelligence of the agents in the field of being humans.',
        url: 'https://www.fbi.gov/',
    },
    {   
        name: 'The Avengers',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Symbol_from_Marvel%27s_The_Avengers_logo.svg/1754px-Symbol_from_Marvel%27s_The_Avengers_logo.svg.png',
        startdate: '10/Jan/1996',
        enddate: '02/Feb/2000',
        role: 'Calculations specialist',
        description: 'Calulate the trajectory of the Moon each day to ensure it is not moving.',
        url: 'https://marvelcinematicuniverse.fandom.com/es/wiki/The_Avengers',
    },
    {
        name: 'Nasa',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/2449px-NASA_logo.svg.png',
        startdate: '3/Feb/2000',
        enddate: '01/12/2003',
        role: 'Cofee maker',
        description: 'As head of the division of coffee makers in NASA the main goal was to serve hot cofee to all the employees.',
        url: 'https://www.nasa.gov/', 
    },
    {   
        name: 'FBI',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/FBI_Badge.png',
        startdate: '10/Jan/2004',
        enddate: '02/Feb/1812',
        role: 'Inteligence meter',
        description: 'Calculate de intelligence of the agents in the field of being humans.',
        url: 'https://www.fbi.gov/',
    },
    {   
        name: 'The Avengers',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Symbol_from_Marvel%27s_The_Avengers_logo.svg/1754px-Symbol_from_Marvel%27s_The_Avengers_logo.svg.png',
        startdate: '10/Jan/1996',
        enddate: '02/Feb/2000',
        role: 'Calculations specialist',
        description: 'Calulate the trajectory of the Moon each day to ensure it is not moving.',
        url: 'https://marvelcinematicuniverse.fandom.com/es/wiki/The_Avengers',
    },
    {
        name: 'Nasa',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/2449px-NASA_logo.svg.png',
        startdate: '3/Feb/2000',
        enddate: '01/12/2003',
        role: 'Cofee maker',
        description: 'As head of the division of coffee makers in NASA the main goal was to serve hot cofee to all the employees.',
        url: 'https://www.nasa.gov/', 
    },
    {   
        name: 'FBI',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/FBI_Badge.png',
        startdate: '10/Jan/2004',
        enddate: '02/Feb/1812',
        role: 'Inteligence meter',
        description: 'Calculate de intelligence of the agents in the field of being humans.',
        url: 'https://www.fbi.gov/',
    },
    {   
        name: 'The Avengers',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Symbol_from_Marvel%27s_The_Avengers_logo.svg/1754px-Symbol_from_Marvel%27s_The_Avengers_logo.svg.png',
        startdate: '10/Jan/1996',
        enddate: '02/Feb/2000',
        role: 'Calculations specialist',
        description: 'Calulate the trajectory of the Moon each day to ensure it is not moving.',
        url: 'https://marvelcinematicuniverse.fandom.com/es/wiki/The_Avengers',
    },
    {
        name: 'Nasa',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/2449px-NASA_logo.svg.png',
        startdate: '3/Feb/2000',
        enddate: '01/12/2003',
        role: 'Cofee maker',
        description: 'As head of the division of coffee makers in NASA the main goal was to serve hot cofee to all the employees.',
        url: 'https://www.nasa.gov/', 
    },
    {   
        name: 'FBI',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/FBI_Badge.png',
        startdate: '10/Jan/2004',
        enddate: '02/Feb/1812',
        role: 'Inteligence meter',
        description: 'Calculate de intelligence of the agents in the field of being humans.',
        url: 'https://www.fbi.gov/',
    },
    
]